# Configurate for target.spec,Auto-Created #
CONFIG_NET_4		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_SYNCHRONIZE_GMAC0		=Y
CONFIG_SYNCHRONIZE		=Y
CONFIG_SYNCHRONIZE_COM1		=Y
CONFIG_NET		=Y
CONFIG_SYNCHRONIZE_GPIO2		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_USB		=Y
CONFIG_USB_DEVICE		=Y
