# Configurate for target.spec,Auto-Created #
CONFIG_TA_DISP		=Y
CONFIG_SYNCHRONIZE_0		=Y
CONFIG_SYNCHRONIZE_1		=Y
CONFIG_SYNCHRONIZE_2		=Y
CONFIG_SYNCHRONIZE_3		=Y
CONFIG_TA_DISP		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_NET		=Y
CONFIG_SYNCHRONIZE_COM1		=Y
CONFIG_SYNCHRONIZE_COM2		=Y
CONFIG_SYNCHRONIZE_GMAC0		=Y
