#Configuratefortarget.spec,Auto-Created#
CONFIG_NET_0		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_SYNCHRONIZE_GEM0		=Y
CONFIG_NET		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_USB		=Y
CONFIG_USB_DEVICE		=Y
