#Configuratefortarget.spec,Auto-Created#
CONFIG_ARCH		=arm64
CONFIG_SUB_ARCH		=ftc663
CONFIG_CPU_ENDIAN		=little
CONFIG_CPU_FLOAT		=hard
CONFIG_CPU_CLOCK		=2000
CONFIG_CPU_CORE_NUMBER		=4
CONFIG_CPU_BIT		=64
CONFIG_CPU_SMP		=true
