# Configurate for target.spec,Auto-Created #
CONFIG_NET_0		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_SYNCHRONIZE_RTL8111_8168_8411_PCI_EXPRESS_GIGABIT_ETHERNET_CONTROLLER__8168__0		=Y
CONFIG_SYNCHRONIZE_RTL8111_8168_8411_PCI_EXPRESS_GIGABIT_ETHERNET_CONTROLLER__8168__1		=Y
CONFIG_SYNCHRONIZE_COM1		=Y
CONFIG_SYNCHRONIZE_COM2		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_USB		=Y
CONFIG_USB_DEVICE		=Y
