# Configurate for target.spec,Auto-Created #
CONFIG_ARCH		=arm
CONFIG_SUB_ARCH		=CortexA55
CONFIG_CPU_ENDIAN		=little
CONFIG_CPU_FLOAT		=hard
CONFIG_CPU_CLOCK		=800
CONFIG_CPU_CORE_NUMBER		=2
CONFIG_CPU_BIT		=32
CONFIG_CPU_SMP		=true
