################################################################################
# 自动生成的文件。不要编辑！
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../../src/userAppInit.c 

OBJS += \
./src/userAppInit.o 

DEPS += \
./src/userAppInit.d 



OTHER_OPTION :=
ARCH =__ARM__
# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../../src/%.c
	@echo '正在构建文件： $<'
	@echo '正在调用： GCC C Compiler'
	$(CC) -DDEBUG_INFO=1 -DOS_FAULT_STACK_DEEPTH=4 -DTTOS_RUN_IN_USER -DTTOS_POSIX_API -DCONFIG_DEVICE_COM1=1 -DCONFIG_DEVICE_COM2=1 -DCONFIG_CONSOLE_STDIN=CONFIG_DEVICE_VIRTUAL_TERMINAL_NAME -DCONFIG_CONSOLE_STDOUT=CONFIG_DEVICE_VIRTUAL_TERMINAL_NAME -DENABLE_CPLUSPLUS=0 -ID:/Intewell_V1.8.2_beta/eclipse/workspace/Eca3399c_Test_TTOS_timer_App/src -ID:/Intewell_V1.8.2_beta/eclipse/workspace/Eca3399c_Test_TTOS_timer_App -ID:/Intewell_V1.8.2_beta/eclipse/workspace/Eca3399c_Test_TTOS_timer_App/$(CONFIG_NAME) -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/json -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/include -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/include/net -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/include/sysDriver -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/include/sysDriver/$(CONFIG_ARCH)/$(CONFIG_SUB_ARCH) -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/board/$(CONFIG_ARCH)/start/partition/ttos -ID:/Intewell_V1.8.2_beta/target/RTCore/include/smipc -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/dfs -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/tcpip/netif -ID:/Intewell_V1.8.2_beta/host/pub -I../ -ID:/Intewell_V1.8.2_beta/target/RTCore/include -ID:/Intewell_V1.8.2_beta/target/RTCore/include/igh -ID:/Intewell_V1.8.2_beta/target/RTCore/include/igh/osal -ID:/Intewell_V1.8.2_beta/target/RTCore/include/common -ID:/Intewell_V1.8.2_beta/target/RTCore/include/rtedebug -ID:/Intewell_V1.8.2_beta/target/RTCore/include/ttos -ID:/Intewell_V1.8.2_beta/target/RTCore/include/rpc -ID:/Intewell_V1.8.2_beta/target/RTCore/include/nfs -ID:/Intewell_V1.8.2_beta/target/RTCore/include/driver -ID:/Intewell_V1.8.2_beta/target/RTCore/include/driver/net -ID:/Intewell_V1.8.2_beta/target/RTCore/include/ssk -ID:/Intewell_V1.8.2_beta/target/RTCore/include/partition -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components -ID:/Intewell_V1.8.2_beta/target/RTCore/include/shell -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/dfs -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/sysDriver -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/tcpip/arch -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/sysDriver/$(CONFIG_ARCH)/$(CONFIG_SUB_ARCH) -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/tcpip -ID:/Intewell_V1.8.2_beta/target/RTCore/include/rtl -ID:/Intewell_V1.8.2_beta/target/RTCore/include/ta -ID:/Intewell_V1.8.2_beta/target/RTCore/include/ta/$(CONFIG_ARCH) -ID:/Intewell_V1.8.2_beta/eclipse/workspace/Eca3399c_Test_TTOS_timer_App/src -ID:/Intewell_V1.8.2_beta/target/RTCore/include/cfg -ID:/Intewell_V1.8.2_beta/target/RTCore/include/posix -ID:/Intewell_V1.8.2_beta/target/RTCore/init/partition/ttos -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/soem -ID:/Intewell_V1.8.2_beta/eclipse/workspace/Eca3399c_Test_TTOS_timer_App/src ${OTHER_OPTION} $(USER_OPTION) -D${ARCH}  -O0 -g -Wall -c -fno-builtin -o $@ $< && \
	$(CC) -DDEBUG_INFO=1 -DOS_FAULT_STACK_DEEPTH=4 -DTTOS_RUN_IN_USER -DTTOS_POSIX_API -DCONFIG_DEVICE_COM1=1 -DCONFIG_DEVICE_COM2=1 -DCONFIG_CONSOLE_STDIN=CONFIG_DEVICE_VIRTUAL_TERMINAL_NAME -DCONFIG_CONSOLE_STDOUT=CONFIG_DEVICE_VIRTUAL_TERMINAL_NAME -DENABLE_CPLUSPLUS=0 -ID:/Intewell_V1.8.2_beta/eclipse/workspace/Eca3399c_Test_TTOS_timer_App/src -ID:/Intewell_V1.8.2_beta/eclipse/workspace/Eca3399c_Test_TTOS_timer_App -ID:/Intewell_V1.8.2_beta/eclipse/workspace/Eca3399c_Test_TTOS_timer_App/$(CONFIG_NAME) -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/json -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/include -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/include/net -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/include/sysDriver -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/include/sysDriver/$(CONFIG_ARCH)/$(CONFIG_SUB_ARCH) -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/board/$(CONFIG_ARCH)/start/partition/ttos -ID:/Intewell_V1.8.2_beta/target/RTCore/include/smipc -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/dfs -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/tcpip/netif -ID:/Intewell_V1.8.2_beta/host/pub -I../ -ID:/Intewell_V1.8.2_beta/target/RTCore/include -ID:/Intewell_V1.8.2_beta/target/RTCore/include/igh -ID:/Intewell_V1.8.2_beta/target/RTCore/include/igh/osal -ID:/Intewell_V1.8.2_beta/target/RTCore/include/common -ID:/Intewell_V1.8.2_beta/target/RTCore/include/rtedebug -ID:/Intewell_V1.8.2_beta/target/RTCore/include/ttos -ID:/Intewell_V1.8.2_beta/target/RTCore/include/rpc -ID:/Intewell_V1.8.2_beta/target/RTCore/include/nfs -ID:/Intewell_V1.8.2_beta/target/RTCore/include/driver -ID:/Intewell_V1.8.2_beta/target/RTCore/include/driver/net -ID:/Intewell_V1.8.2_beta/target/RTCore/include/ssk -ID:/Intewell_V1.8.2_beta/target/RTCore/include/partition -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components -ID:/Intewell_V1.8.2_beta/target/RTCore/include/shell -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/dfs -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/sysDriver -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/tcpip/arch -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/sysDriver/$(CONFIG_ARCH)/$(CONFIG_SUB_ARCH) -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/tcpip -ID:/Intewell_V1.8.2_beta/target/RTCore/include/rtl -ID:/Intewell_V1.8.2_beta/target/RTCore/include/ta -ID:/Intewell_V1.8.2_beta/target/RTCore/include/ta/$(CONFIG_ARCH) -ID:/Intewell_V1.8.2_beta/eclipse/workspace/Eca3399c_Test_TTOS_timer_App/src -ID:/Intewell_V1.8.2_beta/target/RTCore/include/cfg -ID:/Intewell_V1.8.2_beta/target/RTCore/include/posix -ID:/Intewell_V1.8.2_beta/target/RTCore/init/partition/ttos -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/soem -ID:/Intewell_V1.8.2_beta/eclipse/workspace/Eca3399c_Test_TTOS_timer_App/src ${OTHER_OPTION} $(USER_OPTION) -D${ARCH}  -O0 -g -Wall -c -fno-builtin -MM -MG -P -w   $< > $(@:%.o=%.d)
	sed -i '1s/^/.\/src\//' $(@:%.o=%.d)
	@echo '已结束构建： $<'
	@echo ' '


COMPILE_COMMAND := $(CC) -DDEBUG_INFO=1 -DOS_FAULT_STACK_DEEPTH=4 -DTTOS_RUN_IN_USER -DTTOS_POSIX_API -DCONFIG_DEVICE_COM1=1 -DCONFIG_DEVICE_COM2=1 -DCONFIG_CONSOLE_STDIN=CONFIG_DEVICE_VIRTUAL_TERMINAL_NAME -DCONFIG_CONSOLE_STDOUT=CONFIG_DEVICE_VIRTUAL_TERMINAL_NAME -DENABLE_CPLUSPLUS=0 -ID:/Intewell_V1.8.2_beta/eclipse/workspace/Eca3399c_Test_TTOS_timer_App -ID:/Intewell_V1.8.2_beta/eclipse/workspace/Eca3399c_Test_TTOS_timer_App/$(CONFIG_NAME) -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/json -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/include -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/include/net -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/include/sysDriver -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/include/sysDriver/$(CONFIG_ARCH)/$(CONFIG_SUB_ARCH) -ID:/Intewell_V1.8.2_beta/target/RTCore/bsp/board/$(CONFIG_ARCH)/start/partition/ttos -ID:/Intewell_V1.8.2_beta/target/RTCore/include/smipc -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/dfs -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/tcpip/netif -ID:/Intewell_V1.8.2_beta/host/pub -I../ -ID:/Intewell_V1.8.2_beta/target/RTCore/include -ID:/Intewell_V1.8.2_beta/target/RTCore/include/igh -ID:/Intewell_V1.8.2_beta/target/RTCore/include/igh/osal -ID:/Intewell_V1.8.2_beta/target/RTCore/include/common -ID:/Intewell_V1.8.2_beta/target/RTCore/include/rtedebug -ID:/Intewell_V1.8.2_beta/target/RTCore/include/ttos -ID:/Intewell_V1.8.2_beta/target/RTCore/include/rpc -ID:/Intewell_V1.8.2_beta/target/RTCore/include/nfs -ID:/Intewell_V1.8.2_beta/target/RTCore/include/driver -ID:/Intewell_V1.8.2_beta/target/RTCore/include/driver/net -ID:/Intewell_V1.8.2_beta/target/RTCore/include/ssk -ID:/Intewell_V1.8.2_beta/target/RTCore/include/partition -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components -ID:/Intewell_V1.8.2_beta/target/RTCore/include/shell -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/dfs -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/sysDriver -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/tcpip/arch -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/sysDriver/$(CONFIG_ARCH)/$(CONFIG_SUB_ARCH) -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/tcpip -ID:/Intewell_V1.8.2_beta/target/RTCore/include/rtl -ID:/Intewell_V1.8.2_beta/target/RTCore/include/ta -ID:/Intewell_V1.8.2_beta/target/RTCore/include/ta/$(CONFIG_ARCH) -ID:/Intewell_V1.8.2_beta/eclipse/workspace/Eca3399c_Test_TTOS_timer_App/src -ID:/Intewell_V1.8.2_beta/target/RTCore/include/cfg -ID:/Intewell_V1.8.2_beta/target/RTCore/include/posix -ID:/Intewell_V1.8.2_beta/target/RTCore/init/partition/ttos -ID:/Intewell_V1.8.2_beta/target/RTCore/include/components/soem ${OTHER_OPTION} $(USER_OPTION) -D${ARCH}  -O0 -g -Wall -c -fno-builtin -o