# Configurate for target.spec,Auto-Created #
CONFIG_NET_0		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_SYNCHRONIZE		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_NET_0		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_SYNCHRONIZE		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_TA_CHANNEL		=Y
