# Configurate for target.spec,Auto-Created #
CONFIG_TA_DISP		=Y
CONFIG_SYNCHRONIZE_3		=Y
CONFIG_TA_DISP		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_NET		=Y
CONFIG_SYNCHRONIZE_COM3		=Y
CONFIG_SYNCHRONIZE_GEM0		=Y
