# Configurate for target.spec,Auto-Created #
CONFIG_TA_DISP		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_NET		=Y
CONFIG_SYNCHRONIZE_COM1		=Y
CONFIG_SYNCHRONIZE_GMAC0		=Y
CONFIG_NET		=Y
CONFIG_SYNCHRONIZE_CAN0		=Y
CONFIG_TA_DISP		=Y
