# Configurate for target.spec,Auto-Created #
CONFIG_NET_5		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_SYNCHRONIZE		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_NET_4		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_SYNCHRONIZE_GMAC0		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_TA_CHANNEL		=Y
CONFIG_TA_CHANNEL		=Y
